name: 构建 Turnip

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      BUILD_VERSION: ${{ inputs.version }}
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装编译环境
        run: |
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt update
          sudo apt install -y build-essential flex bison glslang-tools meson

      - name: 执行编译脚本
        run: bash ./turnip_builder.sh

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: mainline-turnip-v${{ inputs.version }}
          path: |
            /tmp/mainline-turnip-V${{ inputs.version }}.zip
            /tmp/mainline-turnip-sync-V${{ inputs.version }}.zip
